apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-{{ .Values.app.version }}
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.group }}
    version: {{ .Values.app.version }}
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      version: {{ .Values.app.version }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        group: {{ .Values.app.group }}
        version: {{ .Values.app.version }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.container.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.app.container.port }}
          envFrom:
            {{- range .Values.app.container.config }}
            - configMapRef:
                name: {{ .name }}
            {{- end}}
          env:
            {{- range .Values.app.container.env}}
            - name: {{ .key}}
              value: {{ .value}}
            {{- end}}
